/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal.Componentes;

import javax.swing.JOptionPane;

/**
 *
 * @author leomi
 */
public class CheckBox extends javax.swing.JFrame {

    /**
     * Creates new form CaixaDeOpcao
     */
    public CheckBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chbTecnologiaDaInformacao = new javax.swing.JCheckBox();
        chbSaude = new javax.swing.JCheckBox();
        lblTitulo = new javax.swing.JLabel();
        chbFinancas = new javax.swing.JCheckBox();
        btnExibirPreferencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SistemaIFBA");

        chbTecnologiaDaInformacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbTecnologiaDaInformacao.setText("Tecnologia da Informação");

        chbSaude.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbSaude.setText("Saúde");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Áreas de Interesse para Livros:");

        chbFinancas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbFinancas.setText("Finanças");

        btnExibirPreferencias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExibirPreferencias.setText("Exibir Preferências");
        btnExibirPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirPreferenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbTecnologiaDaInformacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnExibirPreferencias)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(chbTecnologiaDaInformacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSaude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFinancas)
                .addGap(34, 34, 34)
                .addComponent(btnExibirPreferencias)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirPreferenciasActionPerformed
        String preferencias = "";
        
        if(chbTecnologiaDaInformacao.isSelected())
        {
            preferencias += "-Tecnologia da Informação\n";
        }
        
        if(chbSaude.isSelected())
        {
            preferencias += "-Saúde\n";
        }
        
        if(chbFinancas.isSelected())
        {
            preferencias += "-Finanças\n"; 
        }
        
        JOptionPane.showMessageDialog(this, preferencias);
    }//GEN-LAST:event_btnExibirPreferenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibirPreferencias;
    private javax.swing.JCheckBox chbFinancas;
    private javax.swing.JCheckBox chbSaude;
    private javax.swing.JCheckBox chbTecnologiaDaInformacao;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
