/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaSwing_00.ExemplosDeUtilizacaoDeComponentes;

import JavaSwing_05.ExemplosCompletos.GerenciarUsuario.TelaGerenciarUsuario;

/**
 *
 * @author leomi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraDeMenusPrincipal = new javax.swing.JMenuBar();
        MenuUsuario = new javax.swing.JMenu();
        MenuClienteCadastrar = new javax.swing.JMenuItem();
        MenuClienteAlterar = new javax.swing.JMenuItem();
        MenuClienteExcluir = new javax.swing.JMenuItem();
        MenuClientePesquisar = new javax.swing.JMenuItem();
        MenuProduto = new javax.swing.JMenu();
        MenuProdutoCadastrar = new javax.swing.JMenuItem();
        MenuProdutoAlterar = new javax.swing.JMenuItem();
        MenuProdutoExcluir = new javax.swing.JMenuItem();
        MenuProdutoPesquisar = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema IFBA");

        BarraDeMenusPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        MenuUsuario.setText("Usuário");
        MenuUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuClienteCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuClienteCadastrar.setText("Cadastrar");
        MenuClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteCadastrarActionPerformed(evt);
            }
        });
        MenuUsuario.add(MenuClienteCadastrar);

        MenuClienteAlterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuClienteAlterar.setText("Alterar");
        MenuUsuario.add(MenuClienteAlterar);

        MenuClienteExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuClienteExcluir.setText("Excluir");
        MenuUsuario.add(MenuClienteExcluir);

        MenuClientePesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuClientePesquisar.setText("Pesquisar");
        MenuUsuario.add(MenuClientePesquisar);

        BarraDeMenusPrincipal.add(MenuUsuario);

        MenuProduto.setText("Produto");
        MenuProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuProdutoCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuProdutoCadastrar.setText("Cadastrar");
        MenuProduto.add(MenuProdutoCadastrar);

        MenuProdutoAlterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuProdutoAlterar.setText("Alterar");
        MenuProduto.add(MenuProdutoAlterar);

        MenuProdutoExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuProdutoExcluir.setText("Excluir");
        MenuProduto.add(MenuProdutoExcluir);

        MenuProdutoPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuProdutoPesquisar.setText("Pesquisar");
        MenuProduto.add(MenuProdutoPesquisar);

        BarraDeMenusPrincipal.add(MenuProduto);

        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        BarraDeMenusPrincipal.add(MenuSair);

        setJMenuBar(BarraDeMenusPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_MenuSairMouseClicked

    private void MenuClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteCadastrarActionPerformed
        TelaGerenciarUsuario telaCadastroUsuario = new TelaGerenciarUsuario();
        telaCadastroUsuario.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        telaCadastroUsuario.setVisible(true);
    }//GEN-LAST:event_MenuClienteCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenusPrincipal;
    private javax.swing.JMenuItem MenuClienteAlterar;
    private javax.swing.JMenuItem MenuClienteCadastrar;
    private javax.swing.JMenuItem MenuClienteExcluir;
    private javax.swing.JMenuItem MenuClientePesquisar;
    private javax.swing.JMenu MenuProduto;
    private javax.swing.JMenuItem MenuProdutoAlterar;
    private javax.swing.JMenuItem MenuProdutoCadastrar;
    private javax.swing.JMenuItem MenuProdutoExcluir;
    private javax.swing.JMenuItem MenuProdutoPesquisar;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu MenuUsuario;
    // End of variables declaration//GEN-END:variables
}
